ДЗ 1
KMA504/2019-2-Atom-Frontend-M-Kulaev pull request #1
Opened 2019-10-07 20:34 UTC by KMA504

# Домашнее задание № 1
Прошу @chexex проверить его.
Что было сделано:
1. Написаны требуемые функции и тесты.
2. Подключён Travis.

2019-10-08 12:12 UTC, chexex requested changes
Необходимо связать репозиторий со сборщиком (travis-ci.org)
Помогут последние слайды с первой лекции.
После того, как репозиторий будет добавлен в сборку, необходимо будет выполнить любой коммит и запушить изменения, чтобы стартануть сборку.

2019-10-08 16:41 UTC, chexex commented
Удали, пожалуйста, package-lock.json, он ломает сборку

2019-10-09 18:57 UTC, chexex commented
travis-ci.com требует гитхаб токена

travis-ci.org подключен правильно

Нужно либо отсоединить travis-ci.COM от гита, либо докинуть туда гитхаб ключ.

2019-10-09 21:15 UTC, KMA504 commented
Спасибо, теперь всё заработало.

2019-10-10 15:37 UTC, chexex approved these changes
Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-10 15:38 UTC, merged

2019-10-10 15:38 UTC, chexex commented
Не забудь поставить фото на портале